### ISSUE TITLE
the parameter allowNonProductionCMSSW doesn't work 

### ISSUE THREAD

**Issue by fanzago** [dmwm/CRAB2#970]
The if - else code in cms_cmssw to catch the value of allowNonProductionCMSSW parameter is wrong:
the parameter name has to be catch in lowercase and the value should be an integer.

Already fixed and committed in git and in afs (CRAB_2_10_2 code) (I know, this is not the correct way to do this thing, we should create a new pre, but an user is using a not production version of cmssw.... https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/7118/1/1/1/1/1.html)

**Comment by belforte** [comment]
thanks Federica, sorry about this.
Anyhow I can understand the lowercase (sorry, never noticed that all config param names are converted to lowercase), but why integer ?
As to "proper way". The proper way is to open an issue first and then refer to it in the commit. So that github keeps the  relationship and allows to navigate from issue to code and viceversa.
I will do that now and I will create a CRAB_2_10_2_patch1.
